"""FastAPI surface for the simulation.

Endpoints wired through slice 02:
  /state, /step, /reset, /seed, /catalog, /forecast, /build, /demolish.
All mutating calls (success or failure) are appended to
runs/{run_id}/actions.jsonl.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from fastapi import FastAPI, HTTPException
from fastapi.responses import FileResponse
from fastapi.staticfiles import StaticFiles
from pydantic import BaseModel, Field
from starlette.types import Scope

from world.action_log import ActionLog
from world.catalog import build_catalog
from world.scoring import score as score_world
from world.sim import World
from world.subsurface import SEISMIC_DEFAULT_SIZE


class _NoStoreStaticFiles(StaticFiles):
    async def get_response(self, path: str, scope: Scope):
        response = await super().get_response(path, scope)
        response.headers["Cache-Control"] = "no-store"
        return response


# Baselines are committed to the repo root under `baselines/seed_{N}.json`,
# generated by slice 14 (scripted agent run). The /score endpoint reads
# the file matching the active seed; missing files return 404 so callers
# know to run the scripted agent before scoring.
BASELINES_DIR: Path = Path(__file__).resolve().parent.parent / "baselines"


class ResetBody(BaseModel):
    seed: int | None = None


class StepBody(BaseModel):
    days: int = Field(default=7, ge=1, le=7)


class BuildBody(BaseModel):
    tile_type: str
    x: int
    y: int


class DemolishBody(BaseModel):
    x: int
    y: int


class SurveyBody(BaseModel):
    x: int
    y: int
    size: int = Field(default=SEISMIC_DEFAULT_SIZE)


class DrillBody(BaseModel):
    x: int
    y: int
    target_z: int
    well_type: str = Field(default="production")


class WellControlBody(BaseModel):
    well_id: str
    rate_bbl_day: float


class RefineryControlBody(BaseModel):
    refinery_id: str
    rate_bbl_day: float


class BatteryControlBody(BaseModel):
    tile_id: str
    charge_kw: float


def create_app(
    world: World | None = None,
    action_log: ActionLog | None = None,
    *,
    runs_root: str = "runs",
) -> FastAPI:
    app = FastAPI(title="Energy-AI Nexus", version="0.1.0")

    # When no World is provided, allocate one wired to the canonical
    # `runs/` root so the recorder (slice 03) writes metadata + per-day
    # state + final.json. The default ActionLog then lands its
    # `actions.jsonl` inside the recorder's run folder so a single run
    # directory holds every artifact for the session.
    if world is None:
        world = World(runs_root=runs_root)
    if action_log is None:
        run_id = world.recorder.run_id if world.recorder is not None else None
        action_log = ActionLog(root=runs_root, run_id=run_id)
    app.state.world = world
    app.state.action_log = action_log
    # When the world owns a recorder, /reset reallocates the run folder
    # under it — actions.jsonl must follow so a single run dir holds
    # every artifact for the post-reset session. This flag is set only
    # for callers that took the default `action_log` path; callers who
    # passed their own ActionLog have explicit lifecycle control.
    app.state._action_log_follows_recorder = action_log is not None and (
        world.recorder is not None and action_log.dir == world.recorder.dir
    )
    app.state._runs_root = runs_root

    @app.get("/seed")
    def get_seed() -> dict[str, int]:
        return {"seed": app.state.world.state.seed}

    @app.get("/catalog")
    def get_catalog() -> dict[str, Any]:
        return build_catalog()

    @app.get("/state")
    def get_state() -> dict[str, Any]:
        return app.state.world.state_dict()

    @app.get("/events")
    def get_events() -> dict[str, Any]:
        s = app.state.world.state
        return {
            "active": list(s.active_events),
            "historical": list(s.historical_events),
            "regulatory_tightenings_applied": s.regulatory_tightenings_applied,
        }

    @app.get("/score")
    def get_score() -> dict[str, Any]:
        seed = app.state.world.state.seed
        baseline_path = BASELINES_DIR / f"seed_{seed}.json"
        if not baseline_path.exists():
            raise HTTPException(status_code=404, detail="baseline_missing")
        payload = json.loads(baseline_path.read_text())
        p_ref = float(payload["p_ref"])
        t_ref = float(payload["t_ref"])
        return score_world(app.state.world, p_ref, t_ref)

    @app.get("/forecast")
    def get_forecast(hours: int = 24) -> list[dict[str, Any]]:
        if hours < 1 or hours > 168:
            raise HTTPException(status_code=400, detail="hours must be in [1, 168]")
        return app.state.world.forecast(hours=hours)

    @app.post("/reset")
    def post_reset(body: ResetBody) -> dict[str, Any]:
        params = body.model_dump()
        try:
            app.state.world.reset(seed=body.seed)
            result = {
                "ok": True,
                "treasury_after": app.state.world.state.treasury,
                "result": {"seed": app.state.world.state.seed, "day": 0},
            }
            # If the action log was co-located with the (now-finalized)
            # recorder, rebind it to the fresh recorder's folder so the
            # post-reset session keeps actions.jsonl alongside the new
            # states.jsonl / metadata.json / final.json. Callers who
            # passed their own ActionLog stay where they put it.
            if (
                getattr(app.state, "_action_log_follows_recorder", False)
                and app.state.world.recorder is not None
            ):
                app.state.action_log = ActionLog(
                    root=app.state._runs_root,
                    run_id=app.state.world.recorder.run_id,
                )
            app.state.action_log.append("/reset", params, ok=True, result=result["result"])
            return result
        except Exception as exc:  # pragma: no cover - defensive
            app.state.action_log.append("/reset", params, ok=False, error=str(exc))
            raise

    @app.post("/step")
    def post_step(body: StepBody) -> dict[str, Any]:
        params = body.model_dump()
        try:
            summary = app.state.world.step(days=body.days)
            result = {
                "ok": True,
                "day_completed": summary.day_completed,
                "summary": summary.summary,
                "treasury_after": summary.treasury_after,
            }
            app.state.action_log.append(
                "/step", params, ok=True, result={"day_completed": summary.day_completed}
            )
            return result
        except ValueError as exc:
            app.state.action_log.append("/step", params, ok=False, error=str(exc))
            raise HTTPException(status_code=400, detail=str(exc)) from exc

    @app.post("/build")
    def post_build(body: BuildBody) -> dict[str, Any]:
        params = body.model_dump()
        result = app.state.world.build(body.tile_type, body.x, body.y)
        app.state.action_log.append(
            "/build",
            params,
            ok=result["ok"],
            error=result.get("error"),
            result=result.get("result"),
        )
        return result

    @app.post("/survey")
    def post_survey(body: SurveyBody) -> dict[str, Any]:
        params = body.model_dump()
        result = app.state.world.survey(body.x, body.y, body.size)
        # Strip the bulky voxel array out of the action log entry; agents that
        # care can re-read /reservoirs. Keep cost/size/x/y for forensics.
        log_result: Any = None
        if result.get("result"):
            log_result = {k: v for k, v in result["result"].items() if k != "voxels"}
            log_result["n_voxels"] = len(result["result"].get("voxels", []))
        app.state.action_log.append(
            "/survey",
            params,
            ok=result["ok"],
            error=result.get("error"),
            result=log_result,
        )
        return result

    @app.get("/reservoirs")
    def get_reservoirs(min_oil: float = 0.0, top_k: int = 100) -> dict[str, Any]:
        if top_k < 1 or top_k > 4096:
            raise HTTPException(status_code=400, detail="top_k must be in [1, 4096]")
        return app.state.world.reservoirs(min_oil=min_oil, top_k=top_k)

    @app.post("/drill")
    def post_drill(body: DrillBody) -> dict[str, Any]:
        params = body.model_dump()
        result = app.state.world.drill(body.x, body.y, body.target_z, body.well_type)
        app.state.action_log.append(
            "/drill",
            params,
            ok=result["ok"],
            error=result.get("error"),
            result=result.get("result"),
        )
        return result

    @app.post("/control/well")
    def post_control_well(body: WellControlBody) -> dict[str, Any]:
        params = body.model_dump()
        result = app.state.world.control_well(body.well_id, body.rate_bbl_day)
        app.state.action_log.append(
            "/control/well",
            params,
            ok=result["ok"],
            error=result.get("error"),
            result=result.get("result"),
        )
        return result

    @app.post("/control/battery")
    def post_control_battery(body: BatteryControlBody) -> dict[str, Any]:
        params = body.model_dump()
        result = app.state.world.control_battery(body.tile_id, body.charge_kw)
        app.state.action_log.append(
            "/control/battery",
            params,
            ok=result["ok"],
            error=result.get("error"),
            result=result.get("result"),
        )
        return result

    @app.post("/control/refinery")
    def post_control_refinery(body: RefineryControlBody) -> dict[str, Any]:
        params = body.model_dump()
        result = app.state.world.control_refinery(body.refinery_id, body.rate_bbl_day)
        app.state.action_log.append(
            "/control/refinery",
            params,
            ok=result["ok"],
            error=result.get("error"),
            result=result.get("result"),
        )
        return result

    @app.post("/demolish")
    def post_demolish(body: DemolishBody) -> dict[str, Any]:
        params = body.model_dump()
        result = app.state.world.demolish(body.x, body.y)
        app.state.action_log.append(
            "/demolish",
            params,
            ok=result["ok"],
            error=result.get("error"),
            result=result.get("result"),
        )
        return result

    # Static UI -----------------------------------------------------------
    # `no-store` keeps the hot-reload loop honest during dev: every page load
    # re-fetches app.js / style.css / index.html so working-tree edits show
    # up without a hard-reload. The UI is tiny and local; no caching needed.
    ui_dir = Path(__file__).parent / "ui"
    if ui_dir.exists():
        app.mount("/ui", _NoStoreStaticFiles(directory=ui_dir), name="ui")

        @app.get("/")
        def index() -> FileResponse:
            return FileResponse(
                ui_dir / "index.html",
                headers={"Cache-Control": "no-store"},
            )

    return app


app = create_app()
